name: Build AOSP for Xiaomi Mi 11

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev repo

      - name: Initialize AOSP
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r1
          repo sync -c -j4

      - name: Add device tree and kernel
        run: |
          git clone https://github.com/soumyo19/android_device_xiaomi_venus.git device/xiaomi/venus
          git clone https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git kernel/xiaomi/venus

      - name: Build AOSP
        run: |
          source build/envsetup.sh
          lunch aosp_venus-eng
          mka -j$(nproc) target-files-package
          
      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: aosp-rom
          path: out/target/product/venus/*.zip
